blank_issues_enabled: false
contact_links:
  - name: "Contributing guide"
    url: "./CONTRIBUTING.md"
  - name: "Code of Conduct"
    url: "./CODE_OF_CONDUCT.md"
template:
  - name: "Bug report"
    about: "Report a bug"
    title: "[Bug]: "
  - name: "Feature request"
    about: "Suggest an improvement"
  - name: "Discussion"
    about: "Open-ended feedback or ideas"
