name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # or 3.10 / 3.9 if that's your version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        sudo apt-get update
        sudo apt-get install -y xvfb
    - name: Run tests with Xvfb
      run: |
        xvfb-run --auto-servernum -- pytest
