name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies and system libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-timeout pytest-mock
        pip install pytest
        sudo apt-get update
        sudo apt-get install -y xvfb libxcb-xinerama0 libxkbcommon-x11-0

    - name: Run tests with Xvfb (headless)
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        xvfb-run --auto-servernum -- pytest --timeout=60
